### ISSUE TITLE
Design a first front-front-end page 

### ISSUE THREAD

**Issue by LucasProgrammierStube** [DevvitIO/CMS#12]
We need to design a medium like overview page. 
After the design process we need to code it.

**Comment by jorda13456** [comment]
![sitesubmission](https://user-images.githubusercontent.com/6192494/32297397-73d7042e-bf25-11e7-9c4d-61cbb301bf0d.png)

This is my submission for the overview page.  It would be nice to see other's submissions or have them submit feedback.

**Comment by hotborsh** [comment]
I think it looks pretty good. Can we get a PSD or any other format other than PNG to get the colors/fonts/widths/etc?

**Comment by hotborsh** [comment]
http://www.filedropper.com/websitemockup here's the link for the psd.

**Comment by gand988** [comment]
really cool job man, i will use your color palette for the adminstrator section

**Comment by LucasProgrammierStube** [comment]
Jup, I agree. Well done!
