### ISSUE TITLE
Login and verification

### ISSUE THREAD

**Issue by LucasProgrammierStube** [DevvitIO/CMS#14]
This is just an old issue combinded in one so its clearer.

We need to have a simple sign-up and log-in screen.
We also need a redirection if your logged out.

~The verification page needs to be extended with a GitHub log-in feature and a Google log-in feature. So you can login and register faster and kind of more valid.~

EDIT 1: We stroke out this feature for now.

**Comment by jorda13456** [comment]
![register](https://user-images.githubusercontent.com/6192494/32401009-102f9dea-c0de-11e7-915e-696665cf4d30.png)

This is my submission for the register page
