### ISSUE TITLE
Feature and design discussion 

### ISSUE THREAD

**Issue by LucasProgrammierStube** [DevvitIO/CMS#2]
What you see now are my personal whishes for our CMS you are heavily endorsed to comment your own ideas on the bottom of this page.

The target is that we can easily edit websites. We don't want the edit much of the design. We just want to set images and edit text add a few links are. we  can add more features later on.

Front end: 

- A basic mixed blogging software like medium.com and something like Typo3. (It has to be clean and easy.) 

- A password locked gate for the CMS. Maybe with Google or other social media integration. Possibility to reset the password.

- Some statistics like how many people watched the website or how many viewers from this specific county.

- Editor page with a text editor. That can format text like any other blog post (e.g. bold text, code inside the text, header, link)

- A tool that sets an image for the header so we can build different but static websites.

- Some easy error messages with bootstrap eventually. 

- An auto safe function that saves the database on which we store the edited text.

After we set our features and design decisson I will create a few issues on that we can work on.

**Comment by KenavR** [comment]
My suggestion is starting with a [Medium](https://medium.com/) like project and extending it afterwards.

### Features for Medium like project

- Sign In with Google, FB, Github, Twitter, ... (create one/two issues for each)
- Write ONE article  (text formatting)
- Label/Categorize an article
- Write comments 
- Track statistics for each article
- Autosave
- editorial features (draft, pre-release, release,...)
- Index page, with some articles and a search function
- ...

### Extensions 
- Login/Register without SM
- Menus
- Link between pages/articles
- Extend the article editor with stuff like video, graphs, ...
- permission structure
- file upload
- Code view
- sign in with LDAP service
- ...

**Comment by hotborsh** [comment]
I can make a barebone layout for the front page. I think we can start with something simillar to a Wordpress/Medium styled list of posts on the front page. A simple list of posts going from top to bottom with posters Name, post date, post title, post image and an excerpt of the post content. Is that ok?
+ we can add a tag list in the sidebar (like on medium).
