### ISSUE TITLE
Mockup rebuild via e.g. photoshop

### ISSUE THREAD

**Issue by LucasProgrammierStube** [DevvitIO/CMS#9]
We need someone than builds a perfect mockup from the example in the readme.md. So the front end devs can do their job better and faster.

**Comment by gand988** [comment]
I will make a mockup of it

**Comment by LucasProgrammierStube** [comment]
nice

**Comment by gand988** [comment]
So, I propose this mockup. There will be a lot of icon to add but is just a general idea and a palette color. 
Icon are coming from:  [Font awesome](http://fontawesome.io/icons/#search). 
Tell me if you like the idea ;)
![cms](https://user-images.githubusercontent.com/22740406/32185831-a27436de-bda0-11e7-9900-5da980b4c3c9.png)

**Comment by LucasProgrammierStube** [comment]
It's pretty nice. In my opinion the color scheme isn't the best, but the design is great.  Well done

**Comment by gand988** [comment]
yes, i wasn't sure about the color scheme. that is definitely a things to change.

**Comment by LucasProgrammierStube** [comment]
We can make a few suggestions and then vote about it

**Comment by gand988** [comment]
Or better, we can use different theme. Can be more easy for the menagment , don't you think? We can set some scss for it.

**Comment by LucasProgrammierStube** [comment]
Good idea
